name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  Make_GitHub_Release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step_version.outputs.version }}
      upload_url: ${{ steps.step_upload_url.outputs.upload_url }}
    steps:
      - id: step_version
        run: echo "::set-output name=version::${{ steps.package_version.outputs.version }}"
        
      - id: step_upload_url
        run: echo "::set-output name=upload_url::${{ steps.create_release.outputs.upload_url }}"
      
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Upload package to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
        asset_path: ./dist/*
        asset_name: pca_pwa-${{ github.event.release.name }}.tar.gz
        asset_content_type: application/gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
